name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3 
    - name: Set up node
      uses: actions/setup-node@v3
      with:
        python-version: ${{ matrix.python-version }}
        node-version: 16
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip freeze > requirements.txt
        pip install -r requirements.txt
        npm ci
        npm test
        npm start
